// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCLpLjeRFicv9qY1Z-YGEP8UOWXhdUmo0',
    appId: '1:449794720316:android:16379562a3c2096b7af939',
    messagingSenderId: '449794720316',
    projectId: 'duseca-test-nabeel',
    storageBucket: 'duseca-test-nabeel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDnySA9YXyPX4MN5EZkQIOj6qEyd5aqs',
    appId: '1:449794720316:ios:fd5d8759668366927af939',
    messagingSenderId: '449794720316',
    projectId: 'duseca-test-nabeel',
    storageBucket: 'duseca-test-nabeel.appspot.com',
    iosBundleId: 'com.duseca.youapptest.ios',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF0oYzT_W8VSp_nJAs2JX3Z75JMpOnZ8I',
    appId: '1:449794720316:web:7999eb23456a08607af939',
    messagingSenderId: '449794720316',
    projectId: 'duseca-test-nabeel',
    authDomain: 'duseca-test-nabeel.firebaseapp.com',
    storageBucket: 'duseca-test-nabeel.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDnySA9YXyPX4MN5EZkQIOj6qEyd5aqs',
    appId: '1:449794720316:ios:3d83636a1843d0f97af939',
    messagingSenderId: '449794720316',
    projectId: 'duseca-test-nabeel',
    storageBucket: 'duseca-test-nabeel.appspot.com',
    iosBundleId: 'com.duseca.yourapptest.yourApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF0oYzT_W8VSp_nJAs2JX3Z75JMpOnZ8I',
    appId: '1:449794720316:web:681e1ba8c8bf44097af939',
    messagingSenderId: '449794720316',
    projectId: 'duseca-test-nabeel',
    authDomain: 'duseca-test-nabeel.firebaseapp.com',
    storageBucket: 'duseca-test-nabeel.appspot.com',
  );

}
